### ISSUE TITLE
Define list of API endpoints

### ISSUE THREAD

**Issue by Loenike** [Passiolife/passio_devops#13]
### Include list of API endpoints

_______________
General query + used by OD training pipeline:
- [ ] query for labelname https://github.com/Passiolife/data_client/blob/630ce3c0341cc1db5af59926eeaab450c501f262/data_client/db_utils.py#L88
currently looks like: `"SELECT displaylabelname FROM dict WHERE labelname=X".`
With the new data model: `"SELECT labelname FROM labels WHERE labelid=X"`

https://app.zenhub.com/workspaces/data-tools-5e577a28bce7533ef816019a/issues/passiolife/bulk_inspector/28

_______________
Essential for OD training pipeline:

- [ ] asset data for OD in a formatted/processed way - opening a separate issue for this, since it includes a specific formatting of the API response: https://github.com/Passiolife/passio_devops/issues/12

_______________
Essential API endpoints for Bulk Inspector:

- [ ] I think @brandonparis shared those in here: 
https://github.com/Passiolife/bulk_inspector/issues/10
_______________

TBC

**Comment by Loenike** [comment]
I'll close this, we are keeping track of the separate API endpoints in separate tickets.
